[build]
  command = "npm run build"
  publish = "build"    # or "build", or "docs" — must match your actual outDir
[[redirects]]
  from = "/*.pdf"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
